package com.composetest.core.router.enums

enum class ModuleNavGraph {
    NEWS_NAV_GRAPH,
    DESIGN_SYSTEM_NAV_GRAPH,
    LOGIN_NAV_GRAPH,
    ROOT_NAV_GRAPH,
    EXCHANGE_NAV_GRAPH,
    ACCOUNT_NAV_GRAPH,
    WEATHER_FORECAST_NAV_GRAPH,
    CONFIGURATION_NAV_GRAPH,
    HOME_ROOT_NAV_GRAPH,
    CONFIGURATION_ROOT_NAV_GRAPH,
}