package com.composetest.core.router.enums

enum class ModuleNavGraph {
    NEWS_FEATURE,
    DESIGN_SYSTEM_FEATURE,
    LOGIN_FEATURE,
    ROOT_FEATURE,
    EXCHANGE_FEATURE,
    ACCOUNT_FEATURE,
    WEATHER_FORECAST_FEATURE,
    CONFIGURATION_FEATURE,
    HOME_ROOT_FEATURE,
    CONFIGURATION_ROOT_FEATURE,
}